version: "3.5"

networks:
  common_network:
    external:
      name: common_network  # must match the actual name of the network created in the external file


services:
  portfolio_next:
    container_name: portfolio_next
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      network: common_network  # only when DOCKER_BUILDKIT=0
      args:
        - BASE_URL=$BASE_URL
        - S3_SERVER_ADDRESS=$S3_SERVER_ADDRESS
        - REVALIDATE_TOKEN=$REVALIDATE_TOKEN
    restart: always
    networks:
      - common_network
    ports:
      - 3000:3000
    environment:  # during runtime
      - BASE_URL=$BASE_URL
      - S3_SERVER_ADDRESS=$S3_SERVER_ADDRESS
      - REVALIDATE_TOKEN=$REVALIDATE_TOKEN
#      - MAIL_USERNAME=$MAIL_USERNAME
#      - MAIL_PASSWORD=$MAIL_PASSWORD
#      - OAUTH_CLIENTID=$OAUTH_CLIENTID
#      - OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET
#      - OAUTH_REFRESH_TOKEN=$OAUTH_REFRESH_TOKEN
#      - ACCESS_TOKEN=$ACCESS_TOKEN
#      - RECEIVING_EMAILS=$RECEIVING_EMAILS



