workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - fetch-artifacts
  - build-cms
  - deploy-cms
  - build-next  # cms must be already available in order to execute next static build
  - deploy-next

variables:
  BACKEND_IMAGE_TAG_FILENAME: backend_image_tag.txt

get_backend_image_tag: # from previous successful job
  stage: fetch-artifacts
  before_script:
    - apk add unzip
    - apk add curl
  script:
    - |
      curl --request GET --location --output artifacts.zip \
      --url "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/download?job=build_backend" \
      --header "PRIVATE-TOKEN: glpat-oQ58wU8M49YMi6eYSWqS"
    - unzip artifacts.zip
    - PREV_BACKEND_IMAGE_TAG=$(<${BACKEND_IMAGE_TAG_FILENAME})
    - echo "${SERVICE_NAME}_IMAGE_TAG=${PREV_BACKEND_IMAGE_TAG}" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  except: # not executed if there are changes to the sources
    changes:
      - backend/**/*


build_backend:
  stage: build-cms
  image: docker:20.10.17
  variables:
    # using "docker" as the host is only possible if you alias the service below
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    SERVICE_NAME: "cms_strapi"
  services:
    - name: docker:20.10.17-dind
      alias: docker
      command: [ "--tls=false" ]
  before_script:
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/$SERVICE_NAME
    - apk add jq # install app to parse package.json
    - export PACKAGE_VERSION=$(cat backend/package.json | jq -r .version)
    - export IMAGE_TAG=$PACKAGE_VERSION.$CI_PIPELINE_IID
    - echo "IMAGE_TAG=$IMAGE_TAG"
    - echo "${SERVICE_NAME}_IMAGE_TAG"=$IMAGE_TAG
    - echo "${SERVICE_NAME}_IMAGE_TAG=${IMAGE_TAG}" >> build.env
    - echo "${IMAGE_TAG}" > "${BACKEND_IMAGE_TAG_FILENAME}"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./backend
    - docker push $IMAGE_NAME:$IMAGE_TAG
  artifacts: # by default uploaded to all following stages if not specified in dependencies
    name: "$CI_JOB_NAME"
    paths:
      - backend_image_tag.txt
    reports:
      dotenv: build.env # loaded in all subsequent jobs (must be relative to working directory of .gitlab-ci.yml)
#  rules: # TODO uncomment this
#    - if: $PREV_BACKEND_IMAGE_TAG == ""
#      when: always
#    - if: $PREV_BACKEND_IMAGE_TAG != ""
#      changes:
#        - backend/**/*
#      when: always
#    - when: never



deploy_backend:
  stage: deploy-cms
  variables:
    SERVICE_NAME: "cms_strapi"
    PATH_BCK: "/home/ubuntu/applications/portfolio/cms"
  before_script:
    - chmod 400 $WS_KEY # private key
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/$SERVICE_NAME
    - export IMAGE_TAG=$(eval "echo \${${SERVICE_NAME}_IMAGE_TAG}") # use nested substitution for sh
    - echo $IMAGE_NAME
    - echo "$SERVICE_NAME"_IMAGE_TAG
    - echo $IMAGE_TAG
    - cat $CMS_ENV > .CMS_ENV
    - ls -htla
  script:
    - ssh -o StrictHostKeyChecking=no -i $WS_KEY ubuntu@$WS_HOST "if [ ! -d ${PATH_BCK} ]; then mkdir -p ${PATH_BCK}; fi;"
    - scp -o StrictHostKeyChecking=no -i $WS_KEY backend/docker-compose.yml postgres-init-db.sh .CMS_ENV ubuntu@$WS_HOST:${PATH_BCK}/
    - ssh -o StrictHostKeyChecking=no -i $WS_KEY ubuntu@$WS_HOST "
      cd ${PATH_BCK} &&
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      export DC_IMAGE_NAME=$IMAGE_NAME &&
      export DC_IMAGE_TAG=$IMAGE_TAG &&
      set -o allexport &&
      source .CMS_ENV &&
      set +o allexport &&
      rm .CMS_ENV &&
      ls -htla &&
      docker exec -i postgres bash -c "POSTGRES_USER=$DATABASE_USERNAME; DATABASE_NAME=$DATABASE_NAME; $(<postgres-init-db.sh)" &&
      { docker network create common_network || true } &&
      docker-compose down &&
      docker-compose up -d"
  resource_group: dev # fix The deployment job is older than the previously succeeded deployment job, and therefore cannot be run

build_frontend: # can't use needs here because not the same or earlier stage is referred to
  stage: build-next
  image: docker:20.10.17
  variables:
    # using "docker" as the host is only possible if you alias the service below
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    SERVICE_NAME: "portfolio_next"
  services:
    - name: docker:20.10.17-dind
      alias: docker
      command: [ "--tls=false" ]
  before_script:
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/$SERVICE_NAME
    - apk add jq # install app to parse package.json
    - export PACKAGE_VERSION=$(cat frontend/package.json | jq -r .version)
    - export IMAGE_TAG=$PACKAGE_VERSION.$CI_PIPELINE_IID
    - echo "IMAGE_TAG=$IMAGE_TAG"
    - echo "${SERVICE_NAME}_IMAGE_TAG"=$IMAGE_TAG
    - echo "${SERVICE_NAME}_IMAGE_TAG=${IMAGE_TAG}" >> build.env
    - set -o allexport
    - source $NEXT_ENV
    - set +o allexport
    - echo $IMAGE_HOST_NAME
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_BUILDKIT=0  # allows networking during build
    - docker network create common_network || true
    - docker-compose -f ./frontend/docker-compose.yml build
    - docker push $IMAGE_NAME:$IMAGE_TAG
  artifacts: # by default uploaded to all following stages if not specified in dependencies
    reports:
      dotenv: build.env # loaded in all subsequent jobs (must be relative to working directory of .gitlab-ci.yml)

deploy_frontend:
  stage: deploy-next
  variables:
    SERVICE_NAME: "portfolio_next"
    PATH_FRONT: "/home/ubuntu/applications/portfolio/next"
  before_script:
    - chmod 400 $WS_KEY # private key
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/$SERVICE_NAME
    - export IMAGE_TAG=$(eval "echo \${${SERVICE_NAME}_IMAGE_TAG}") # use nested substitution for sh
    - echo $IMAGE_NAME
    - echo "$SERVICE_NAME"_IMAGE_TAG
    - echo $IMAGE_TAG
    - cat $NEXT_ENV > .NEXT_ENV
    - ls -htla
  script:
    - ssh -o StrictHostKeyChecking=no -i $WS_KEY ubuntu@$WS_HOST "if [ ! -d ${PATH_FRONT} ]; then mkdir -p ${PATH_FRONT}; fi;"
    - scp -o StrictHostKeyChecking=no -i $WS_KEY frontend/docker-compose.yml .NEXT_ENV frontend/Dockerfile ubuntu@$WS_HOST:${PATH_FRONT}/
    - ssh -o StrictHostKeyChecking=no -i $WS_KEY ubuntu@$WS_HOST "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      export IMAGE_NAME=$IMAGE_NAME &&
      export IMAGE_TAG=$IMAGE_TAG &&
      cd ${PATH_FRONT} &&
      set -o allexport &&
      source .NEXT_ENV &&
      set +o allexport &&
      rm .NEXT_ENV &&
      docker-compose down &&
      docker-compose up --no-build -d"
  resource_group: dev # fix The deployment job is older than the previously succeeded deployment job, and therefore cannot be run