version: "3.5"
# Instructions:
# docker network create common_network || true && docker-compose -f docker-compose.oci.prod.yml build --no-cache && docker-compose -f docker-compose.oci.prod.yml up

networks:
  common_network:
    external:
      name: common_network  # must match the actual name of the network created in the external file


services:
  cms_strapi:
    container_name: cms_strapi
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    restart: always
    networks:
      - common_network
    expose:
      - ${PORT} # 1337
    ports:
      - 1338:${PORT} # TODO images will be served from file storage directly
    environment:
      - HOST=$HOST
      - PORT=$PORT
      - APP_KEYS=$APP_KEYS
      - API_TOKEN_SALT=$API_TOKEN_SALT
      - ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - JWT_SECRET=$JWT_SECRET




