import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';

const BASE_URL = "http://localhost:1337/api"

export async function getStaticProps() {
    try {
        const res = await axios.get(`${BASE_URL}/homepage`)
        console.log(res)
        return {
            props: {
                homepageData: res.data
            }
        }
    } catch (e) {
        console.log(e)
    }

}

export default function Home({homepageData}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1 className="text-3xl font-bold underline">
                    {homepageData.data.attributes.Heading}
                </h1>
            </main>

            <footer>

            </footer>
        </div>
    )
}
